# Generated by Django 4.1.1 on 2023-12-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_course_schedule_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
